# Generated by Django 6.0 on 2025-12-09 05:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the book/file', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description or summary', null=True)),
                ('file', models.FileField(help_text='Only PDF, JPEG formats allowed', upload_to='books/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpeg', 'jpg'])])),
                ('year_published', models.IntegerField(blank=True, help_text='Year the book was published', null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost of the book (0 = free)', max_digits=10)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('followers', 'Followers Only')], default='private', help_text='Who can view this file', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='File is available for download')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('downloads_count', models.IntegerField(default=0, help_text='Number of downloads')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
