# Generated by Django 6.0 on 2025-12-10 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_enrolleddata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrolleddata',
            options={'ordering': ['-created_at'], 'verbose_name': 'Enrolled Data', 'verbose_name_plural': 'Enrolled Data'},
        ),
        migrations.AlterField(
            model_name='enrolleddata',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='enrolleddata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
    ]
